version: "3.9"

services:
  nginx:
    container_name: nginx
    image: nginx:alpine3.18
    networks:
      - "website"
    ports:
      - "80:80"
    volumes:
      - "./src:/var/www/html"
      - "./config/default.conf:/etc/nginx/conf.d/default.conf"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
  maraidb:
    container_name: database
    image: mariadb:latest
    networks:
      - "website"
    ports:
      - "3306:3306"
    volumes:
      - "./data:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: debug
      MYSQL_USER: debug
      MYSQL_PASSWORD: debug1234        # Required change this password
      MYSQL_ROOT_PASSWORD: debugln1234 # Required change this password

    restart: always
  php:
    container_name: php
    image: php:8.2-fpm-alpine3.17
    ports:
      - "9000:9000"
    networks:
      - "website"
    volumes:
      - "./src:/var/www/html"
      - "/etc/localtime:/etc/localtime:ro"
    command:
      - /bin/sh
      - -c
      - |
        echo "security.limit_extensions = .php .phtml .php3 .php4 .php5 .html .htm" >> /usr/local/etc/php-fpm.d/www.conf
        php-fpm
    restart: always

networks:
  website: {}
